<?php
/**
 * @file
 *
 */

/*
 * Implements of hook_init()
 */
function manageinfo_init() {
}

/**
 * Implements hook_menu()
 */
function manageinfo_menu() {
  $items = array();

  $items['manage/evaluation/create'] = array(
    'title' => 'Create Evaluation',
    'page callback' => '_manageinfo_evaluation_create',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/manageinfo_node_create.page.inc',
  );
  $items['manage/evaluation/create-form-page'] = array(
    'title' => 'Create Evaluation',
    'page callback' => '_manageinfo_evaluation_create_form_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/manageinfo_node_create_form.page.inc',
  );

  $items['manage/meeting/create'] = array(
    'title' => 'Schedule Meeting',
    'page callback' => '_manageinfo_meeting_create',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/manageinfo_node_create.page.inc',
  );
  $items['manage/meeting/list'] = array(
    'title' => 'Meeting List',
    'page callback' => '_manageinfo_meeting_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'subpage/list/manageinfo_meeting_list.page.inc',
  );

  $items['manage/program/create'] = array(
    'title' => 'Program List',
    'page callback' => '_terminfo_add_program',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/manageinfo_term_create.page.inc',
  );
  $items['manage/program/list'] = array(
    'title' => 'Program List',
    'page callback' => '_manageinfo_program_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'subpage/list/manageinfo_program_list.page.inc',
  );

  $items['manage/question-lib/create'] = array(
    'title' => 'Add Question',
    'page callback' => '_terminfo_add_question_lib',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/manageinfo_term_create.page.inc',
  );
  $items['manage/question-lib/list'] = array(
    'title' => 'Question List',
    'page callback' => '_manageinfo_question_lib_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'subpage/list/manageinfo_question_lib_list.page.inc',
  );

  $items['manage/question-set/create'] = array(
    'title' => 'Add Question Set',
    'page callback' => '_terminfo_add_question_set',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/manageinfo_term_create.page.inc',
  );
  $items['manage/question-set/list'] = array(
    'title' => 'Question List',
    'page callback' => '_manageinfo_question_set_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'subpage/list/manageinfo_question_set_list.page.inc',
  );

  return $items;
}

