<?php
/**
 * @file
 *
 */

/*
 * Implements of hook_init()
 */
function shopinfo_init() {
}

/**
 * Implements hook_menu()
 */
function shopinfo_menu() {
  $items = array();

  $items['siteview/shop/list'] = array(
    'title' => 'Shop List',
    'page callback' => '_shopinfo_shop_list',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'inc/shopinfo_shop_list.page.inc',
  );

  return $items;
}

