<?php
/**
 * @file
 *
 */

/*
 * Implementation of hook_init()
 */
function nodeinfo_init() {
}

/**
 * Implements hook_menu()
 */

/**
 * Implements hook_form_alter()
 */
function nodeinfo_form_alter(&$form, &$form_state, $form_id) {
  /**
   * ginseng node form
   */
  if ($form_id == 'ginseng_node_form') {
    /**
     * hide title field, and revise node title is optional instead of required mandatory
     */
    $form['title']['#type'] = 'hidden';
    $form['title']['#required'] = FALSE;
  }

}

/**
 * Implements hook_node_insert.
 */

/**
 * Implements hook_node_presave().
 * Act on a node being inserted or updated.
 */
function nodeinfo_node_presave($node) {
  _nodeinfo_nodetitle_set_title($node);
}

/**
 * add automatic node title.
 */
function _nodeinfo_nodetitle_set_title(&$node) {
  if ($node->type == 'ginseng') {
    $node->title = t('Ginseng Product');
  }

}
